### ISSUE TITLE
Feature Request: HEX editor in online theme editor/creator

### ISSUE THREAD

**Issue by zaneshaw** [Troplo/BetterCompass#3]
Can we get some sort of HEX colour input for the theme colour attributes? It's a bit tedious to export the theme, edit the values, and importing again. Thanks!

**Comment by Troplo** [comment]
Hi, I've gone ahead and added the custom hex input in the latest update, along with some other editor improvements such as adding a manual color picker as well, hopefully this resolves your issue.

**Comment by zaneshaw** [comment]
Thank you! 😄
